#  Template Java Spring Boot App for Elastic Beanstalk

#  This template allows you to deploy your application as code using AWS Elastic Beanstalk.
#  The workflow allows validate, linting and security scans on feature branches (as well as master).
#  The Spring Boot App will be validated and deployed after the code is merged to master.

# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY, $AWS_DEFAULT_REGION setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/aws-elasticbeanstalk-deploy/src/master/README.md

image: atlassian/default-image:3

pipelines:
    branches:
        master:
        - step:
            name: Deploy to AWS
            deployment: test
            image: atlassian/pipelines-awscli
            script:
                - aws deploy push --application-name $APPLICATION_NAME --s3-location s3://$S3_BUCKET/$S3_KEY --ignore-hidden-files
                - aws deploy create-deployment --application-name $APPLICATION_NAME --s3-location bucket=$S3_BUCKET,key=$S3_KEY,bundleType=zip --deployment-group-name $DEPLOYMENT_GROUP_NAME
