version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Moving to server ...
      - cd server/server
      - echo Current Directory ... 
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(basename ./build/libs/*.jar)
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/server/server/build/libs/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'
