export const SineRunning = {
  activatedBgColor: "#DDECDA",
  activatedTextColor: "#46A133",
  excitedBgColor: "#F6E3E3",
  excitedTextColor: "#EC6969",
  beforeBgColor: "#E0E0E0",
  beforeTextColor: "#8D94A0",
  defaultBgColor: "#DAD8FB",
  defaultTextColor: "#7974E7",
};

export const SiweRunning = {
  activatedTextColor: "#7974E7",
  activatedBgColor: "#DAD8FB",
  excitedBgColor: "#E0E0E0",
  excitedTextColor: "#8D94A0",
  beforeBgColor: "#E0E0E0",
  beforeTextColor: "#8D94A0",
  defaultBgColor: "#F6E3E3",
  defaultTextColor: "#EC6969",
};

export const lightTheme = {
  taxiFrameColor:"#E8F3E6",
  taxiPartyColor:"#DAD8FB",
  taxiRouteText: "#354938",
  homeBgColor: "#f2f4f6",
  homeCompColor: "white",
  mainTextColor: "black",
  subTextColor: "gray",
  busBgColor: "white",
  busCompColor: "white",
  scheduleBgColor: "white",
  scheduleCompColor: "white",
  tableHeader: "#f5f5f5",
  tableContents: "white",
  tableHeaderText: "#6d7582",
  tableContentsText: "#6d7582",
  routeContents: "white",
  routeName: "#6d7582",
  busListHeader: "#fafbfb",
  busList: "white",
  totalTimeText: "#353c49",
  arrivalTimeText: "#747c88",
  busNumberText: "black",
  busStationText: "#747c88",
  busBorderColor: "#d3d7dc",
  noticeHader: "white",
};

export const darkTheme = {
  homeBgColor: "#2c2c2c",
  homeCompColor: "#383838",
  mainTextColor: "white",
  subTextColor: "#d2dae2",
  busBgColor: "#2c2c2c",
  busCompColor: "#383838",
  scheduleBgColor: "#2c2c2c",
  scheduleCompColor: "#383838",
  tableHeader: "#383838",
  tableContents: "#2c2c2c",
  tableHeaderText: "white",
  tableContentsText: "#d2dae2",
  routeContents: "#2c2c2c",
  routeName: "#d2dae2",
  busListHeader: "#2F2F2F",
  busList: "#383838",
  totalTimeText: "#C5C5C5",
  arrivalTimeText: "#d2dae2",
  busNumberText: "white",
  busStationText: "#E2E2E2",
  busBorderColor: "#757575",
  noticeHader: "#2c2c2c",
};
