spring:
  profiles:
    active: ${PROFILE}
  datasource:
    username: ${DB_USER_ID}
    password: ${DB_USER_PW}
    url: jdbc:mysql://db.mju-bus.com:3306/mju-bus-${DB_ENV}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: GET
            user-name-attribute: id

  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER # Swagger-ui

external:
  naver:
    key: ${NAVER_KEY}
    client-id: ${NAVER_CLIENT_ID}
  apple:
    token-uri: https://appleid.apple.com/auth/token
    audience-uri: https://appleid.apple.com
    client-id: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    bundle-id: com.mjubus.mbus
    private-key: ${APPLE_PRIVATE_KEY}
  kakao:
    validate-uri: https://kapi.kakao.com/v1/user/access_token_info
logging:
  config: classpath:logback-spring.xml

