spring:
  profiles:
    active: local
  datasource:
    username: root
    password: mbaSince2021~
    url: jdbc:mysql://db.mju-bus.com:3306/mju-bus-staging?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER # Swagger-ui

external:
    naver:
        key: MgLSNKb2EsLXMPYq0Ailk5iFa3gWbKxIBl20DIm4
        client-id: p4xiv96tkc
#logging:
#  config: classpath:logback-spring.xml
